name: jobhub CI
on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'develop'

jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Environment Info
        run: |
          echo "Operating System: $(uname)"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Git Ref: $GITHUB_REF"
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test


